import { test } from 'node:test';
import assert from 'node:assert/strict';
import { assertDomainClosure } from '../src/core/domain/closure.js';
import { composeDomainDocument } from '../src/core/document/compose/composeDomainDocument.js';
import { renderDocumentHtml } from '../src/core/renderers/html/renderHtml.js';
import { renderDocumentTypst } from '../src/core/renderers/typst/renderTypst.js';
import type { DomainConversationDetail } from '../src/core/domain/conversationDetail.js';
test('nested resource references are checked before composition; unavailable bytes are backend diagnostics', () => {
    const domain: DomainConversationDetail = { providerId: 'test', id: 'conversation', title: 'Nested', timestamp: null, assets: [], messages: [{ id: 'message', role: 'assistant', content: [{ type: 'list', ordered: false, items: [{ blocks: [{ type: 'quote', blocks: [{ type: 'image', assetId: 'missing', alt: 'Nested figure' }] }] }] }] }] };
    assert.throws(() => assertDomainClosure(domain), /Unregistered Domain asset 'missing' in messages\[0\]/);
    domain.assets.push({ id: 'missing', kind: 'image' });
    const document = composeDomainDocument(domain).document;
    const html = renderDocumentHtml(document, {});
    assert.equal(html.diagnostics.filter(d => d.code === 'HTML_ASSET_UNRESOLVED').length, 1);
    assert.ok(html.html.includes('Nested figure'));
    const diagnostics: string[] = [];
    const pdf = renderDocumentTypst(document, {}, { onDiagnostic(d) { diagnostics.push(d.code); } });
    assert.equal(diagnostics.filter(code => code === 'TYPST_V8_IMAGE_MISSING').length, 1);
    assert.ok(JSON.stringify(pdf).includes('Nested figure'));
});
