// sessionRecovery.ts - Export indexing, developer diagnostics, and export record finalization

export interface SessionLogOptions {
    landedChats?: number;
    totalChats?: number;
    downloadedAssets?: number;
    totalAssets?: number;
    skipped?: number;
    failedChats?: any[];
    failedAttachments?: any[];
    isDevMode?: boolean;
}

export interface FinalizeChatExportContext {
    finalizedChatsSet?: Set<string>;
    chatRecordsMap?: Map<string, any>;
    chatFailedAssetsSet?: Set<string>;
    curIds?: Record<string, any>;
    exportedIds?: Record<string, any>;
    Storage?: any;
    storageAdapter?: any;
    slot?: string;
    onItemExported?: (id: string, record: any) => void;
}

export interface SessionRecoveryModule {
    writeIndexAndMeta: (
        metaResults: any[],
        landedChats: number,
        downloadedAssets: number,
        totalAssets: number,
        writer?: IExportWriter | null
    ) => Promise<void>;
    writeDiagnostics: (
        isDevMode: boolean,
        sessionJson: any,
        fullLogText: string,
        writer?: IExportWriter | null,
        onLog?: (msg: string, level?: string) => void
    ) => Promise<void>;
    buildSessionLogText: (options?: SessionLogOptions) => string;
    finalizeChatExport: (targetId: string, context?: FinalizeChatExportContext) => Promise<boolean>;
    updateSessionStatus: (patch: any) => Promise<void>;
    getExtensionVersion: (customVersion?: string) => string;
}

import { normId as utilsNormId } from "../../utils/utils.js";
import { __resolveModule } from "../../utils/moduleOverrides.js";
import { I18n as I18nStatic } from "../../utils/i18n.js";
import { SessionStore } from "../../storage/sessionStore.js";

const normId = (id?: string | number | null): string => {
    return (((__resolveModule('GeminiUtils', null) as any)?.normId) || utilsNormId)(id);
};

import { EXT_VERSION, getExtensionVersion } from "../../utils/constants.js";
import type { IExportWriter } from "../writers/writerInterface.js";
export { EXT_VERSION, getExtensionVersion };

    async function writeIndexAndMeta(
        metaResults: any[],
        landedChats: number,
        downloadedAssets: number,
        totalAssets: number,
        writer?: IExportWriter | null
    ): Promise<void> {
        if (!metaResults || !metaResults.length) return;
        const I18n = __resolveModule('I18n', I18nStatic);
        const isZh = I18n.getLang && I18n.getLang() === 'zh';
        let indexContent = isZh
            ? `# Gemini 对话索引目录 (Export Index)\n\n> 导出时间: ${new Date().toLocaleString()} · 总会话数: ${landedChats} · 附件数: ${downloadedAssets}/${totalAssets}\n\n| 对话标题 (Title) | 消息数 | 附件 | 原始链接 (URL) | 导出文件 |\n| :--- | :--- | :--- | :--- | :--- |\n`
            : `# Gemini Conversation Export Index\n\n> Export Time: ${new Date().toLocaleString()} · Total Chats: ${landedChats} · Assets: ${downloadedAssets}/${totalAssets}\n\n| Conversation Title | Messages | Assets | Original URL | Exported File |\n| :--- | :--- | :--- | :--- | :--- |\n`;

        for (const meta of metaResults) {
            const safeT = (meta.title || '')
                .replace(/\\/g, '\\\\')
                .replace(/\|/g, '\\|')
                .replace(/\[/g, '\\[')
                .replace(/\]/g, '\\]');
            const linkText = isZh ? '🔗 原文' : '🔗 Link';
            indexContent += `| **[${safeT}](${meta.exportFile})** | ${meta.messageCount} | ${meta.attachmentCount} | [${linkText}](${meta.url}) | \`${meta.exportFile}\` |\n`;
        }
        indexContent += `\n---\n_Generated by Gemini Exporter at ${new Date().toISOString()}_\n`;

        const metaJsonContent = JSON.stringify({
            exportedAt: new Date().toISOString(),
            version: getExtensionVersion(),
            total: metaResults.length,
            conversations: metaResults
        }, null, 2);

        // Phase B (B1): 写出口统一收口到 writer，不再分 folder/writeFileDirect 分支。
        // Phase A (P0-1) 语义：index 写失败 fail-closed，直接外抛。
        if (!writer || typeof writer.writeFile !== 'function') {
            throw new Error('[sessionRecovery] writeIndexAndMeta: IExportWriter is required');
        }
        await writer.writeFile('00_INDEX.md', indexContent);
        await writer.writeFile('meta.json', metaJsonContent);
    }

    function buildSessionLogText({
        landedChats = 0,
        totalChats = 0,
        downloadedAssets = 0,
        totalAssets = 0,
        skipped = 0,
        failedChats = [],
        failedAttachments = [],
        isDevMode = false
    }: SessionLogOptions = {}): string {
        let fullLogText = `=======================================================\n`;
        fullLogText += ` Gemini Exporter Session Log${isDevMode ? ' (Dev Mode)' : ' (Error Report)'}\n`;
        fullLogText += ` Time: ${new Date().toISOString()}\n`;
        fullLogText += ` Summary: Landed ${landedChats}/${totalChats} chats, Assets ${downloadedAssets}/${totalAssets}, Skipped ${skipped}\n`;
        fullLogText += ` Failed Chats: ${failedChats.length}, Failed Assets: ${failedAttachments.length}\n`;
        fullLogText += `=======================================================\n\n`;

        if (failedChats.length > 0) {
            fullLogText += `[FAILED CONVERSATIONS]\n`;
            for (const fc of failedChats) {
                if (typeof fc === 'string') {
                    fullLogText += `  - ${fc}\n`;
                } else {
                    const fcId = fc.id || fc.chatId || 'unknown';
                    const fcTitle = (fc.title || fc.chatTitle || '').slice(0, 60);
                    const fcErr = fc.error || fc.reason || 'unknown';
                    fullLogText += `  - ${fcId} | "${fcTitle}" | ${fcErr}\n`;
                    if (fc.debug && typeof fc.debug === 'object') {
                        try {
                            fullLogText += `    [debug] ${JSON.stringify(fc.debug).slice(0, 800)}\n`;
                        } catch (e) {
                            if (typeof console !== 'undefined' && console.debug) console.debug('[GemExporter:sessionRecovery.ts]', e);
                        }
                    } else if (fc.raw && typeof fc.raw === 'object') {
                        try {
                            fullLogText += `    [raw_preview] ${JSON.stringify(fc.raw).slice(0, 400)}\n`;
                        } catch (e) {
                            if (typeof console !== 'undefined' && console.debug) console.debug('[GemExporter:sessionRecovery.ts]', e);
                        }
                    }
                }
            }
            fullLogText += `\n`;
        }

        if (failedAttachments.length > 0) {
            fullLogText += `[FAILED ASSETS / ATTACHMENTS]\n`;
            for (const fa of failedAttachments) {
                fullLogText += `  - Chat: "${fa.chatTitle || fa.chatId || fa.chat}" | File: "${fa.file}" | Reason: ${fa.error || fa.reason}\n`;
            }
            fullLogText += `\n`;
        }

        return fullLogText;
    }

    async function writeDiagnostics(
        isDevMode: boolean,
        sessionJson: any,
        fullLogText: string,
        writer?: IExportWriter | null,
        onLog: (msg: string, level?: string) => void = (() => {})
    ): Promise<void> {
        try {
            // Phase B (B1): 写出口统一收口到 writer，不再分 folder/writeFileDirect 分支。
            if (!writer || typeof writer.writeFile !== 'function') {
                throw new Error('[sessionRecovery] writeDiagnostics: IExportWriter is required');
            }
            await writer.writeFile('_export_dev.log', fullLogText);
            if (sessionJson.failedAttachments?.length || sessionJson.failedChats?.length) {
                await writer.writeFile('_export_errors.json', JSON.stringify(sessionJson, null, 2));
            }
            if (isDevMode) {
                await writer.writeFile('_export_session_dev.json', JSON.stringify(sessionJson, null, 2));
            }
            const I18n = __resolveModule('I18n', I18nStatic);
            onLog(I18n.t('logDevLogWritten'), 'info');
        } catch (logWriteErr) {
            // Phase A (P0-1): 不再静默吞错。记 console 后外抛，由调用方
            // (exportOrchestrator) 统一 try/catch + onLog，避免"写错误报告失败再写错误报告"递归
            if (typeof console !== 'undefined' && console.error) {
                console.error('Failed to write _export_dev.log', logWriteErr);
            }
            throw logWriteErr;
        }
    }

    async function finalizeChatExport(targetId: string, context: FinalizeChatExportContext = {}): Promise<boolean> {
        const {
            finalizedChatsSet,
            chatRecordsMap,
            chatFailedAssetsSet,
            curIds,
            exportedIds,
            Storage,
            storageAdapter = Storage,
            slot = 'u0',
            onItemExported = (() => {})
        } = context;

        const targetNid = normId(targetId);
        if (finalizedChatsSet && finalizedChatsSet.has(targetNid)) return false;
        const rec = chatRecordsMap ? chatRecordsMap.get(targetNid) : null;
        if (!rec) return false;

        if (chatFailedAssetsSet && chatFailedAssetsSet.has(targetNid)) {
            rec.status = (rec.status === 'empty') ? 'empty' : 'partial';
            rec.hasFailedAssets = true;
        }

        // Persist export record before updating in-memory state.
        // Phase A (P1-4): 只保留 saveExportRecord 一条正式路径 —— mock adapter 必须实现它。
        // 缺失即抛错，不再静默降级到 storageAdapter.set/get 或 chrome.storage 直写。
        if (!storageAdapter || typeof storageAdapter.saveExportRecord !== 'function') {
            throw new Error(
                `[GemExporter:sessionRecovery.ts] storageAdapter.saveExportRecord is required to finalize export for ${targetId} (slot ${slot})`
            );
        }
        try {
            await storageAdapter.saveExportRecord(slot, targetId, rec);
        } catch (e) {
            if (typeof console !== 'undefined' && console.error) {
                console.error('[GemExporter:sessionRecovery.ts] saveExportRecord failed for', targetId, e);
            }
            throw e;
        }

        if (finalizedChatsSet) finalizedChatsSet.add(targetNid);
        if (curIds && targetNid) curIds[targetNid] = rec;
        if (exportedIds && targetNid) exportedIds[targetNid] = rec;

        try {
            onItemExported(targetId, rec);
        } catch (e) {
            if (typeof console !== 'undefined' && console.debug) {
                console.debug('[GemExporter:sessionRecovery.ts] onItemExported callback error', e);
            }
        }
        return true;
    }

    // Serialize session status writes to prevent race conditions
    let sessionStatusWriteChain: Promise<void> = Promise.resolve();

    async function updateSessionStatus(patch: any): Promise<void> {
        const task = sessionStatusWriteChain.then(() => SessionStore.updateSession(patch));
        // Keep the chain alive even if this write fails; the caller still
        // observes the rejection via `task`.
        sessionStatusWriteChain = task.then(() => undefined, () => undefined);
        await task;
    }

export {
    writeIndexAndMeta,
    writeDiagnostics,
    buildSessionLogText,
    finalizeChatExport,
    updateSessionStatus
};

export const SessionRecovery: SessionRecoveryModule = {
    writeIndexAndMeta,
    writeDiagnostics,
    buildSessionLogText,
    finalizeChatExport,
    updateSessionStatus,
    getExtensionVersion
};

export default SessionRecovery;
