// sessionRecovery.js - Export indexing, developer diagnostics, and export record finalization
(function(root, factory) {
    if (typeof define === 'function' && define.amd) {
        define([], factory);
    } else if (typeof module === 'object' && module.exports) {
        module.exports = factory();
    } else {
        root.SessionRecovery = factory();
    }
}(typeof self !== 'undefined' ? self : this, function() {
    'use strict';

    function getExtensionVersion(customVersion) {
        if (customVersion) return customVersion;
        try {
            if (typeof chrome !== 'undefined' && chrome.runtime && chrome.runtime.getManifest) {
                return chrome.runtime.getManifest().version || '1.3.8';
            }
        } catch (e) {
            if (typeof console !== 'undefined' && console.debug) {
                console.debug('[GemExporter:sessionRecovery.js]', e);
            }
        }
        return '1.3.8';
    }

    const getUtils = () => {
        if (typeof GeminiUtils !== 'undefined') return GeminiUtils;
        if (typeof globalThis !== 'undefined' && globalThis.GeminiUtils) return globalThis.GeminiUtils;
        if (typeof require !== 'undefined') {
            try { return require('../../utils/utils.js'); } catch { /* intentional: require fallback in browser context */ }
        }
        return null;
    };

    const normId = (id) => (getUtils()?.normId ? getUtils().normId(id) : String(id || '').replace(/^c_/, '').trim());

    async function writeIndexAndMeta(metaResults, landedChats, downloadedAssets, totalAssets, writeFileDirect, folder, useZip) {
        if (!metaResults || !metaResults.length) return;
        const isZh = typeof I18n !== 'undefined' && I18n.getLang && I18n.getLang() === 'zh';
        let indexContent = isZh
            ? `# Gemini 对话索引目录 (Export Index)\n\n> 导出时间: ${new Date().toLocaleString()} · 总会话数: ${landedChats} · 附件数: ${downloadedAssets}/${totalAssets}\n\n| 对话标题 (Title) | 消息数 | 附件 | 原始链接 (URL) | 导出文件 |\n| :--- | :--- | :--- | :--- | :--- |\n`
            : `# Gemini Conversation Export Index\n\n> Export Time: ${new Date().toLocaleString()} · Total Chats: ${landedChats} · Assets: ${downloadedAssets}/${totalAssets}\n\n| Conversation Title | Messages | Assets | Original URL | Exported File |\n| :--- | :--- | :--- | :--- | :--- |\n`;

        for (const meta of metaResults) {
            const safeT = (meta.title || '')
                .replace(/\\/g, '\\\\')
                .replace(/\|/g, '\\|')
                .replace(/\[/g, '\\[')
                .replace(/\]/g, '\\]');
            const linkText = isZh ? '🔗 原文' : '🔗 Link';
            indexContent += `| **[${safeT}](${meta.exportFile})** | ${meta.messageCount} | ${meta.attachmentCount} | [${linkText}](${meta.url}) | \`${meta.exportFile}\` |\n`;
        }
        indexContent += `\n---\n_Generated by Gemini Exporter at ${new Date().toISOString()}_\n`;

        const metaJsonContent = JSON.stringify({
            exportedAt: new Date().toISOString(),
            version: getExtensionVersion(),
            total: metaResults.length,
            conversations: metaResults
        }, null, 2);

        if (useZip && folder) {
            folder.file('00_INDEX.md', indexContent);
            folder.file('meta.json', metaJsonContent);
        } else if (typeof writeFileDirect === 'function') {
            await writeFileDirect('00_INDEX.md', indexContent);
            await writeFileDirect('meta.json', metaJsonContent);
        }
    }

    function buildSessionLogText({
        landedChats = 0,
        totalChats = 0,
        downloadedAssets = 0,
        totalAssets = 0,
        skipped = 0,
        failedChats = [],
        failedAttachments = [],
        isDevMode = false
    } = {}) {
        let fullLogText = `=======================================================\n`;
        fullLogText += ` Gemini Exporter Session Log${isDevMode ? ' (Dev Mode)' : ' (Error Report)'}\n`;
        fullLogText += ` Time: ${new Date().toISOString()}\n`;
        fullLogText += ` Summary: Landed ${landedChats}/${totalChats} chats, Assets ${downloadedAssets}/${totalAssets}, Skipped ${skipped}\n`;
        fullLogText += ` Failed Chats: ${failedChats.length}, Failed Assets: ${failedAttachments.length}\n`;
        fullLogText += `=======================================================\n\n`;

        if (failedChats.length > 0) {
            fullLogText += `[FAILED CONVERSATIONS]\n`;
            for (const fc of failedChats) {
                if (typeof fc === 'string') {
                    fullLogText += `  - ${fc}\n`;
                } else {
                    const fcId = fc.id || fc.chatId || 'unknown';
                    const fcTitle = (fc.title || fc.chatTitle || '').slice(0, 60);
                    const fcErr = fc.error || fc.reason || 'unknown';
                    fullLogText += `  - ${fcId} | "${fcTitle}" | ${fcErr}\n`;
                    if (fc.debug && typeof fc.debug === 'object') {
                        try {
                            fullLogText += `    [debug] ${JSON.stringify(fc.debug).slice(0, 800)}\n`;
                        } catch (e) {
                            if (typeof console !== 'undefined' && console.debug) console.debug('[GemExporter:sessionRecovery.js]', e);
                        }
                    } else if (fc.raw && typeof fc.raw === 'object') {
                        try {
                            fullLogText += `    [raw_preview] ${JSON.stringify(fc.raw).slice(0, 400)}\n`;
                        } catch (e) {
                            if (typeof console !== 'undefined' && console.debug) console.debug('[GemExporter:sessionRecovery.js]', e);
                        }
                    }
                }
            }
            fullLogText += `\n`;
        }

        if (failedAttachments.length > 0) {
            fullLogText += `[FAILED ASSETS / ATTACHMENTS]\n`;
            for (const fa of failedAttachments) {
                fullLogText += `  - Chat: "${fa.chatTitle || fa.chatId || fa.chat}" | File: "${fa.file}" | Reason: ${fa.error || fa.reason}\n`;
            }
            fullLogText += `\n`;
        }

        return fullLogText;
    }

    async function writeDiagnostics(isDevMode, sessionJson, fullLogText, writeFileDirect, folder, useZip, onLog = (() => {})) {
        try {
            if (useZip && folder) {
                folder.file('_export_dev.log', fullLogText);
                if (sessionJson.failedAttachments.length || sessionJson.failedChats.length) {
                    folder.file('_export_errors.json', JSON.stringify(sessionJson, null, 2));
                }
                if (isDevMode) {
                    folder.file('_export_session_dev.json', JSON.stringify(sessionJson, null, 2));
                }
            } else if (typeof writeFileDirect === 'function') {
                await writeFileDirect('_export_dev.log', fullLogText);
                if (sessionJson.failedAttachments.length || sessionJson.failedChats.length) {
                    await writeFileDirect('_export_errors.json', JSON.stringify(sessionJson, null, 2));
                }
                if (isDevMode) {
                    await writeFileDirect('_export_session_dev.json', JSON.stringify(sessionJson, null, 2));
                }
            }
            onLog(typeof I18n !== 'undefined' ? I18n.t('logDevLogWritten') : '🛠️ [开发者模式] 已自动将完整导出日志与诊断写入 _export_dev.log', 'info');
        } catch (logWriteErr) {
            if (typeof console !== 'undefined' && console.error) {
                console.error('Failed to write _export_dev.log', logWriteErr);
            }
        }
    }

    async function finalizeChatExport(targetId, context = {}) {
        const {
            finalizedChatsSet,
            chatRecordsMap,
            chatFailedAssetsSet,
            curIds,
            exportedIds,
            Storage,
            storageAdapter = Storage,
            slot = 'u0',
            onItemExported = (() => {})
        } = context;

        const targetNid = normId(targetId);
        if (finalizedChatsSet && finalizedChatsSet.has(targetNid)) return false;
        const rec = chatRecordsMap ? chatRecordsMap.get(targetNid) : null;
        if (!rec || (chatFailedAssetsSet && chatFailedAssetsSet.has(targetNid))) return false;

        if (finalizedChatsSet) finalizedChatsSet.add(targetNid);

        if (curIds) {
            curIds[targetId] = rec;
            curIds[targetNid] = rec;
            curIds['c_' + targetNid] = rec;
        }
        if (exportedIds) {
            exportedIds[targetId] = rec;
            exportedIds[targetNid] = rec;
            exportedIds['c_' + targetNid] = rec;
        }

        try {
            if (storageAdapter && typeof storageAdapter.saveExportRecord === 'function') {
                await storageAdapter.saveExportRecord(slot, targetId, rec);
            } else if (storageAdapter && typeof storageAdapter.set === 'function') {
                const expKey = slot === 'u0' ? 'exportedIds' : `gemini_exported_${slot}`;
                await storageAdapter.set({ [expKey]: curIds });
            } else if (typeof chrome !== 'undefined' && chrome.storage && chrome.storage.local) {
                const expKey = slot === 'u0' ? 'exportedIds' : `gemini_exported_${slot}`;
                await chrome.storage.local.set({ [expKey]: curIds });
            }
        } catch (e) {
            if (typeof console !== 'undefined' && console.debug) {
                console.debug('[GemExporter:sessionRecovery.js] saveExportRecord error', e);
            }
        }

        try {
            onItemExported(targetId, rec);
        } catch (e) {
            if (typeof console !== 'undefined' && console.debug) {
                console.debug('[GemExporter:sessionRecovery.js] onItemExported callback error', e);
            }
        }
        return true;
    }

    return {
        writeIndexAndMeta,
        writeDiagnostics,
        buildSessionLogText,
        finalizeChatExport,
        getExtensionVersion
    };
}));
