import type { GeneratedMediaIdentity } from '../../types/conversation.js';

/** Takeout activity timestamps have second precision; RPC retains milliseconds. */
function eventSecond(value: unknown): number | null {
    if (typeof value !== 'number' || !Number.isFinite(value) || value <= 0) return null;
    return Math.floor(value / 1000);
}

export function normalizeRequestId(id: unknown): string | null {
    if (typeof id !== 'string' || !id.trim()) return null;
    const clean = id.trim().toLowerCase().replace(/^r_/, '');
    return /^[0-9a-f]{16}$/.test(clean) ? clean : (clean.length >= 8 ? clean : null);
}

export function normalizeChatId(id: unknown): string {
    if (typeof id !== 'string' && typeof id !== 'number') return '';
    return String(id).trim().replace(/^c_/, '');
}

export function sameGenerationEvent(a: GeneratedMediaIdentity, b: GeneratedMediaIdentity): boolean {
    const aChat = normalizeChatId(a.chatId);
    const bChat = normalizeChatId(b.chatId);
    if (!aChat || !bChat || aChat !== bChat) {
        return false;
    }

    const aReq = normalizeRequestId(a.providerRequestId);
    const bReq = normalizeRequestId(b.providerRequestId);
    if (aReq && bReq) {
        return aReq === bReq;
    }
    return a.generationOrdinal === b.generationOrdinal
        && eventSecond(a.time) !== null && eventSecond(a.time) === eventSecond(b.time)
        && !!a.prompt && a.prompt.trim() === b.prompt?.trim();
}

/** Resolve only a unique prompt/time event and its sole response, never a first/last turn guess. */
export function findGenerationModelMessage(chat: any, generation: GeneratedMediaIdentity): any | null {
    if (chat?.id && normalizeChatId(chat.id) !== normalizeChatId(generation.chatId)) return null;
    const messages = Array.isArray(chat?.messages) ? chat.messages : [];

    const targetReq = normalizeRequestId(generation.providerRequestId);
    if (targetReq) {
        // 1. Direct match on model message providerRequestId
        const direct = messages.filter((m: any) =>
            (m.role === 'model' || m.role === 'assistant') &&
            normalizeRequestId(m.providerRequestId) === targetReq
        );
        if (direct.length === 1) return direct[0];

        // 2. User message whose id or providerRequestId matches targetReq
        for (let i = 0; i < messages.length; i++) {
            const m = messages[i];
            if (m.role === 'user' && (normalizeRequestId(m.providerRequestId) === targetReq || normalizeRequestId(m.id) === targetReq || normalizeRequestId(m.turnId) === targetReq)) {
                for (let j = i + 1; j < messages.length; j++) {
                    if (messages[j].role === 'model' || messages[j].role === 'assistant') {
                        return messages[j];
                    }
                }
            }
        }
    }

    const marked = messages.filter((m: any) => m.generation && sameGenerationEvent(m.generation, generation));
    if (marked.length === 1) return marked[0];
    if (marked.length > 1 || eventSecond(generation.time) === null || !generation.prompt) return null;
    const users = messages.map((m: any, index: number) => ({ m, index })).filter(({ m }: any) =>
        m.role === 'user' && typeof m.content === 'string'
        && m.content.trim() === generation.prompt!.trim()
        && eventSecond(m.timestamp) === eventSecond(generation.time));
    if (users.length !== 1) return null;
    const models = [];
    for (let i = users[0].index + 1; i < messages.length && messages[i].role !== 'user'; i++) {
        if (messages[i].role === 'model' || messages[i].role === 'assistant') models.push(messages[i]);
    }
    return models.length === 1 ? models[0] : null;
}

function hasReliableGenerationIdentity(image: any, generation: GeneratedMediaIdentity): boolean {
    if (!image || typeof image !== 'object') return false;
    // 1. Explicitly marked as generated by parser
    if (image.isGenerated === true) return true;

    // 2. Has matching providerRequestId
    const genReq = normalizeRequestId(generation.providerRequestId);
    if (genReq) {
        const imgReq = normalizeRequestId(image.providerRequestId || image.generation?.providerRequestId);
        if (imgReq && imgReq === genReq) return true;
    }

    // 3. Has matching generation identity
    if (image.generation && sameGenerationEvent(image.generation, generation)) {
        return true;
    }

    return false;
}

export function hasGenerationImage(message: any, generation: GeneratedMediaIdentity): boolean {
    const rawImages = [...(message?.images || []), ...(message?.attachments || [])].filter(Boolean);

    // Only inspect images with reliable generation identity.
    // Ordinary inline/grounding images (isGenerated !== true) MUST NEVER be treated as generated images.
    const candidateImages = rawImages.filter((img: any) => hasReliableGenerationIdentity(img, generation));
    if (candidateImages.length === 0) {
        return false;
    }

    const genReq = normalizeRequestId(generation.providerRequestId);
    const genOrd = generation.imageOrdinal;

    // Check images with providerRequestId
    if (genReq) {
        for (const image of candidateImages) {
            const imgReq = normalizeRequestId(image.providerRequestId || image.generation?.providerRequestId);
            if (imgReq === genReq) {
                const imgOrd = image.imageOrdinal ?? image.generation?.imageOrdinal ?? 0;
                const targetOrd = genOrd ?? 0;
                if (imgOrd === targetOrd) {
                    if (!image.generation) image.generation = { ...generation, turnId: message.id };
                    message.generation = { ...generation, turnId: message.id };
                    return true;
                }
            }
        }
        // If message itself is tagged with this providerRequestId and contains candidate generated images
        const msgReq = normalizeRequestId(message.providerRequestId || message.generation?.providerRequestId);
        if (msgReq === genReq) {
            if ((genOrd === undefined || genOrd === 0) && (generation.imageCount === 1 || candidateImages.length === 1)) {
                if (!candidateImages[0].generation) candidateImages[0].generation = { ...generation, turnId: message.id };
                message.generation = { ...generation, turnId: message.id };
                return true;
            }
            for (const image of candidateImages) {
                const imgOrd = image.imageOrdinal ?? image.generation?.imageOrdinal ?? 0;
                if (imgOrd === (genOrd ?? 0)) {
                    if (!image.generation) image.generation = { ...generation, turnId: message.id };
                    message.generation = { ...generation, turnId: message.id };
                    return true;
                }
            }
        }
    }

    // Check matching generation identity on candidate images
    for (const image of candidateImages) {
        if (image.generation && sameGenerationEvent(image.generation, generation)) {
            if (generation.imageOrdinal !== undefined && image.generation.imageOrdinal !== undefined) {
                if (image.generation.imageOrdinal === generation.imageOrdinal) return true;
            } else if (generation.imageCount === 1) {
                return true;
            }
        }
    }

    // Fallback: A single-image event where model message has exactly ONE image explicitly marked isGenerated === true.
    if (generation.imageCount === 1 && (genOrd === undefined || genOrd === 0)) {
        const explicitlyGen = candidateImages.filter((image: any) => image.isGenerated === true);
        if (explicitlyGen.length === 1) {
            const target = explicitlyGen[0];
            if (!target.generation) target.generation = { ...generation, turnId: message.id };
            message.generation = { ...generation, turnId: message.id };
            return true;
        }
    }

    return false;
}
